language: android

android:
  components:
    - build-tools-21.1.1
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: false
