language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - extra-android-m2repository
    - android-23

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: false
